### ISSUE TITLE
FCGI server taking longer time to send data to client

### ISSUE THREAD

**Issue by shravanhudekar** [siemens/siapp-sdk#11]
Hi,

demo siapp with FCGI client developed in node.js loaded on CP-8050.
this application is used to fetch data from CP8050 for post processing.
its observed that FCGI server taking almost **1sec** to send data to client over local network on same machine.

 **FCGX_PutStr(out_buffer, strlen(out_buffer), cgi.out);
URL: /edgedata/get response, out_buffer len: 199354  size of s_read_list: 880**

when same application is simulated locally on system it takes < 100ms.

**Comment by lukas-wimmer** [comment]
This is a performance problem of the demo code and not a problem of the underlying API. Therefore, we are closing this issue. The web server API is not an official API and is not built or tested for fast response time.
