### ISSUE TITLE
Time Sync SIAPP with CP time zone  

### ISSUE THREAD

**Issue by lesterdsouza-extsiemens** [siemens/siapp-sdk#12]
Unable to access `cat /etc/timezone ` from the host 

![image](https://github.com/user-attachments/assets/3870eec5-c78f-4950-ab41-e93d9e463e2d)

How can we sync the deployed SIAPP container time with the host time i.e. CP 8050 ?

**Comment by lukas-wimmer** [comment]
Hello, we will take a look and get back to you.

**Comment by lukas-wimmer** [comment]
Hi, we decided to set the TZ environment variable for the container which establish the local time zone in linux.


 ```
> cat /proc/1/environ
TZ=SYSNT-01:00SYSDT-02:00,M03.5.0/02:00,M10.5.0/03:00
```


Calling date with different TZ offset values
 ```
> TZ='SYSNT-01:00SYSDT-02:00,M03.5.0/02:00,M10.5.0/03:00' date
Tue Oct  1 14:46:28 SYSDT 2024
```
 ```
> TZ='SYSNT-01:00SYSDT-03:00,M03.5.0/02:00,M10.5.0/03:00' date
Tue Oct  1 15:46:34 SYSDT 2024
```
for more info about the format have a look into https://data.iana.org/time-zones/theory.html#:~:text=A%20proleptic%20TZ%20value%20like,past%2C%20present%2C%20and%20future.

The function will be available with the next upcoming release which is planned for November 2024 (CPCI85 6.0).
