### ISSUE TITLE
Cannot run build.bat in WSL

### ISSUE THREAD

**Issue by MadhavPK** [siemens/siapp-sdk#3]
Hello SiAPP developers,
I am using Docker in WSL Ubuntu 20.04. I can neither run the **_build.bat_** in PS nor in WSL. Is there a **_.sh_** equivalent for the build file?
Thanks.

**Comment by lukas-wimmer** [comment]
Hello, currently we are working on a platform independent solution of our SIAPP-SDK. As soon as this is available we will inform you here.

**Comment by BoehMarkus** [comment]
This issue has been fixed in commit 95bf2ffbf8fea47b5b81927c8fdf83bba5141202
