### ISSUE TITLE
Getting Docker error

### ISSUE THREAD

**Issue by MadhavPK** [siemens/siapp-sdk#4]
Hello,
I am getting docker error when I am working with docker desktop.
![image](https://user-images.githubusercontent.com/31771892/145341515-a4c2e4bb-30f2-4f87-819a-64ea4b9c5504.png)<br><br>

Previously I had made changes to **_build.bat_** file to work with the docker running on the WSL. This is the error I get
![image](https://user-images.githubusercontent.com/31771892/145343490-642c933c-e61f-4599-83f6-c01e917f92ad.png)
Please find the modified **_build.bat_** file renamed to **_build_with_wsl.txt_**.
[build_with_wsl.txt](https://github.com/siemens/siapp-sdk/files/7682619/build_with_wsl.txt)

**Comment by lukas-wimmer** [comment]
Hello,

please use one of the following commands to create the DemoProject with Docker Desktop on Windows 

.\build.bat .\DemoProject
.\build.bat DemoProject

**Comment by MadhavPK** [comment]
Thank you @lukas-wimmer,
`.\build.bat DemoProject` worked.
