### ISSUE TITLE
Unable to build CodeSnippets

### ISSUE THREAD

**Issue by MadhavPK** [siemens/siapp-sdk#5]
Hello,
I am using Docker in WSL Ubuntu 20.04. I am facing an issue while building _**CodeSnippet**_ project in WSL using python3
![image](https://user-images.githubusercontent.com/31771892/161232597-16e72f18-d8b7-4264-81ef-00b3e411d3bd.png)
Same is with **_DemoProject_**
![image](https://user-images.githubusercontent.com/31771892/161233779-655a33e1-df24-4f7e-8521-3cc5826fdf85.png)

and **_DemoSshd_**
![image](https://user-images.githubusercontent.com/31771892/161234159-bb23a84b-9918-478c-a00b-d8d57235722e.png)

**Comment by lukas-wimmer** [comment]
Hello, can you send us the following information?

- WSL version
- WSL distribution
- Docker version

Seems like your docker installation does not support multi arch. 

You can try to use qemu instead:
- Put "qemu-arm-static" into your Docker Root Directory.
- Add "COPY qemu-arm-static /usr/bin" at the beginning of your dockerfile

**Comment by MadhavPK** [comment]
Hello Lukas,
WSL Version: 2
WSL distribution: Ubuntu 20.04.4 LTS
Docker version: 20.10.13

Thank you very much Lukas for the suggestion. After following the **_[README](https://github.com/multiarch/qemu-user-static)_**, I was able to build and run all 3 projects and **siapp** file is generated in _**build**_ directory.
The issue I am facing now is that the SIAPP EMULATION and Data Simulation cmd prompts are not opening but applications seems to be working fine.

**Comment by lukas-wimmer** [comment]
We have discussed the problem internally. Currently, a pure command line prompt like in WSL is unfortunately not supported. But we will put the problem on our feature list.
